azs:
- name: z1

vm_types:
- name: basic

disk_types:
- name: 1gb
  disk_size: 1000

networks:
- name: shared
  type: manual
  subnets:
  - range: 10.244.99.0/24
    static: [10.244.99.2-10.244.99.9]
    reserved:
    - 10.244.99.250 - 10.244.99.255
    gateway: 10.244.99.1
    az: z1

compilation:
  workers: 2
  reuse_compilation_vms: true
  vm_type: basic
  network: shared
  az: z1
